FROM python:3.11.4

COPY ./dbt_support/dbt /app
COPY _dbt /app/_dbt
WORKDIR /app

RUN pip3 install -r requirements.txt

ENV DBT_PROFILES_DIR=/app/_dbt/
ENV DBT_PROJECT_DIR=/app/_dbt/

# CMD [ "dbt", "build" ]