services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: ${PASSWORD}
    container_name: postgres-db
    ports:
      - "5445:5432"
    tty: true
  
  my_python:
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    container_name: python-container
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      PASSWORD: ${PASSWORD}
      USER: ${USER}
