services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: 1234
    container_name: postgres-db
    ports:
      - "5445:5432"
    tty: true
  
  my_python:
    build: 
      context: ./
      dockerfile: Dockerfile
    tty: true
    container_name: python-container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      PASSWORD: 1234
      DB_USER: postgres

